name : str = "Pakistan"
print(name) # print
print(type(name)) # type
print(id(name)) # physical address
print([i for i in dir(name) if "__" not in i]) # methods and attributes
'''[    'capitalize',
        'casefold',
        'center',
        'count',
        'encode',
        'endswith',
        'expandtabs',
        'find',
        'format',
        'format_map',
        'index',
        'isalnum',
        'isalpha',
        'isascii',
        'isdecimal',
        'isdigit',
        'isidentifier',
        'islower',
        'isnumeric',
        'isprintable',
        'isspace',
        'istitle',
        'isupper',
        'join',
        'ljust',
        'lower',
        'lstrip',
        'maketrans',
        'partition',
        'removeprefix',
        'removesuffix',
        'replace',
        'rfind',
        'rindex',
        'rjust',
        'rpartition',
        'rsplit',
        'rstrip',
        'split',
        'splitlines',
        'startswith',
        'strip',
        'swapcase',
        'title',
        'translate',
        'upper',
        'zfill'
    ]'''